//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        public string CLASS1 { get; set; }
        public string NAME { get; set; }
        public string BLA_QTY { get; set; }
        public string BLA_AMT { get; set; }
        public string TOD_QTY { get; set; }
        public string TOD_AMT { get; set; }
        public string TOT_QTY { get; set; }
        public string TOT_AMT { get; set; }
    }
}
