//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int ID { get; set; }
        public string CUST_CODE { get; set; }
        public string CUST_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string UNIFORM { get; set; }
        public string ATTENTION { get; set; }
        public string TELEPHONE { get; set; }
        public string FAX { get; set; }
        public string REMARK { get; set; }
        public string PAY_DATE { get; set; }
        public string PAY_WAY { get; set; }
        public string DISC { get; set; }
        public string BLAAMT { get; set; }
        public string TAXMON { get; set; }
        public string BLAMON { get; set; }
        public string RECAMT { get; set; }
        public string FOWAMT { get; set; }
        public string SAL_NO { get; set; }
        public string PRT_LAB { get; set; }
        public string TAX { get; set; }
        public string TRN_DATE { get; set; }
    }
}
