//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTITEM
    {
        public int id { get; set; }
        public string CUST_CODE { get; set; }
        public string ITEM_NO { get; set; }
        public string SAL_CODE { get; set; }
        public string L_DATE { get; set; }
        public string L_PRICE { get; set; }
        public string L_QTY { get; set; }
        public string COST { get; set; }
        public string REMARK { get; set; }
    }
}
