//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOY
    {
        public string SAL_NO { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public string BLOOD { get; set; }
        public string B_PLACE { get; set; }
        public string BIRTHDAY { get; set; }
        public string ID_NO { get; set; }
        public string MARRY { get; set; }
        public string ADDRESS1 { get; set; }
        public string TEL1 { get; set; }
        public string BBCALL { get; set; }
        public string ADDRESS2 { get; set; }
        public string TEL2 { get; set; }
        public string EDUCAT { get; set; }
        public string EXPERIENC { get; set; }
        public string UNIT { get; set; }
        public string JOB { get; set; }
        public string A_DATE { get; set; }
        public string L_DATE { get; set; }
        public string ATTENTION { get; set; }
        public string RELATION { get; set; }
        public string REL_ADDR { get; set; }
        public string REL_TEL { get; set; }
        public string ACC_NO { get; set; }
        public string SAL_CODE { get; set; }
        public string AMTP1 { get; set; }
        public string AMTP2 { get; set; }
        public string AMTP3 { get; set; }
        public string AMTP4 { get; set; }
        public string AMTP5 { get; set; }
        public string AMTP6 { get; set; }
        public string AMTP8 { get; set; }
        public string AMTP9 { get; set; }
        public string AMTPA { get; set; }
        public string AMTMP { get; set; }
        public string AMTM1 { get; set; }
        public string AMTM2 { get; set; }
        public string AMTM3 { get; set; }
        public string REMARK { get; set; }
        public string IN_DATE { get; set; }
    }
}
