//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public string ITEM_NO { get; set; }
        public string CLASS { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string S_PRICE { get; set; }
        public string C_PRICE { get; set; }
        public string U_PRICE { get; set; }
        public string UNIT { get; set; }
        public string QTY { get; set; }
        public string S1_QTY { get; set; }
        public string S2_QTY { get; set; }
        public string BLA_QTY { get; set; }
        public string P_QTY { get; set; }
        public string R_QTY { get; set; }
        public string G_QTY { get; set; }
        public string I_QTY { get; set; }
        public string TRN_DATE { get; set; }
        public string SDATE { get; set; }
        public string SQTY { get; set; }
    }
}
