//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMON
    {
        public int ID { get; set; }
        public string FACT_CODE { get; set; }
        public string MON_DATE { get; set; }
        public string SAL_AMT { get; set; }
        public string TAX_AMT { get; set; }
        public string REC_AMT { get; set; }
        public string TOT_AMT { get; set; }
        public string BAL1 { get; set; }
        public string AMO1 { get; set; }
        public string AMO2 { get; set; }
        public string AMO3 { get; set; }
        public string DISC { get; set; }
        public string NANO { get; set; }
    }
}
