//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCH
    {
        public int ID { get; set; }
        public string TRN_NO { get; set; }
        public string INV_NO { get; set; }
        public string TRN_DATE { get; set; }
        public string CODE { get; set; }
        public string REMARK1 { get; set; }
        public string TAX { get; set; }
        public string ACC_DATE { get; set; }
        public string ACC_YN { get; set; }
        public string PAY_WAY { get; set; }
        public string PMARK { get; set; }
        public string SUMAMT { get; set; }
        public string TAXAMT { get; set; }
        public string TOTAMT { get; set; }
        public string AMO1 { get; set; }
        public string AMO2 { get; set; }
        public string AMO3 { get; set; }
    }
}
