//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace INV_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECAMT
    {
        public int id { get; set; }
        public string REC_NO { get; set; }
        public string CUST_CODE { get; set; }
        public string REC_MON { get; set; }
        public string TRN_DATE { get; set; }
        public string REC_AMT { get; set; }
        public string CL_AMT { get; set; }
        public string CHNO { get; set; }
        public string CASH { get; set; }
        public string DISC { get; set; }
        public string OTH_REC { get; set; }
        public string D_NO { get; set; }
        public string RMARK { get; set; }
        public string REMARK1 { get; set; }
    }
}
